apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miniodata
  namespace: fiapx
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: fiapx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          args: ["server", "/data", "--console-address", ":9001"]
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef: { name: app-secret, key: MINIO_ROOT_USER }
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef: { name: app-secret, key: MINIO_ROOT_PASSWORD }
            - name: MINIO_PROMETHEUS_AUTH_TYPE
              value: public
          ports:
            - containerPort: 9000
            - containerPort: 9001
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: miniodata
              mountPath: /data
      volumes:
        - name: miniodata
          persistentVolumeClaim:
            claimName: miniodata
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: fiapx
spec:
  selector:
    app: minio
  ports:
    - name: s3
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
